# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'managed': True},
        ),
    ]
