# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160715_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'managed': False},
        ),
    ]
